function getQuanRuler(){
	var strLabel='';
	strLabel='<div class="panelProto panelWrap rulerWrap" data-role="panelProto" data-text="规则显示" style="position: absolute; height: 359.462px; z-index: 0; width: 100%; font-size: 0.2rem; text-align: left; top: 631.59px; left: 0px; word-wrap: break-word; line-height: normal; cursor: move; margin-left: 0px;" iscount="true">'	
				+'<div class="panelContain" style="height: 100%; width: 100%; position: relative; background-color: rgba(0, 0, 0, 0); background-size: 100% 100%; background-repeat: no-repeat;">'		
				+'	<div class="dragImg box panelChild" data-role="imgProto" style="z-index: 0; position: absolute; width: 232px; height: 64.566px; cursor: move; text-align: center; top: 18.0769px; left: 204px; line-height: normal; margin-left: 0px;" iscount="true">'			
				+'		<img src="images/pres/rule.png" style="height: 100%; width: 100%;display:block;">'			
				+'		<span class="objBorder borderLeft proxy" style="height: 65px; display: none;"></span>'			
				+'		<span class="objBorder borderRight proxy" style="height: 65px; display: none;"></span>'				
				+'		<span class="objBorder borderTop proxy" style="width: 232px; display: none;"></span>'			
				+'		<span class="objBorder borderBottom proxy" style="width: 232px; display: none;"></span>'			
				+'		<span class="coor coorBottomRight proxy" style="display: none;"></span>'		
				+'	</div>'		
				+'	<div class="box txtProto panelChild" data-role="txtProto" style="position: absolute; min-height: 0.3rem; z-index: 0; font-size: 0.24rem; height: auto; width: auto; text-align: left; top: 90.3438px; left: 30.7284px; max-width: 100%; word-wrap: break-word; cursor: move; color: rgb(0, 0, 0);" iscount="true">'			
				+'		<div class="txtShuru" style="height: 100%; min-height: 0.3rem; width: 100%; background-color: transparent;">'				
				+'			活动时间'			
				+'		</div>'	
				+'		<span class="coor proxy coorRightCenter" style="display: none;"></span>'				
				+'		<span class="objBorder borderLeft proxy" style="height: 31px; display: none;"></span>'			
				+'		<span class="objBorder borderRight proxy" style="height: 31px; display: none;"></span>'			
				+'		<span class="objBorder borderTop proxy" style="width: 96px; display: none;"></span>'			
				+'		<span class="objBorder borderBottom proxy" style="width: 96px; display: none;"></span>'		
				+'	</div>'		
				+'	<div class="box txtProto panelChild" data-role="txtProto" style="position: absolute; min-height: 0.3rem; z-index: 0; font-size: 0.24rem; height: auto; width: auto; text-align: left; top: 125.703px; left: 29.1659px; max-width: 100%; word-wrap: break-word; cursor: move; color: rgb(153, 153, 153);" iscount="true">'			
				+'		<div class="txtShuru" style="height: 100%; min-height: 0.3rem; width: 100%; background-color: transparent;">'				
				+'			2016年1月18日-2月1日'			
				+'		</div>'			
				+'		<span class="coor proxy coorRightCenter" style="display: none;"></span>'				
				+'		<span class="objBorder borderLeft proxy" style="height: 31px; display: none;"></span>'			
				+'		<span class="objBorder borderRight proxy" style="height: 31px; display: none;"></span>	'		
				+'		<span class="objBorder borderTop proxy" style="width: 257px; display: none;"></span>'			
				+'		<span class="objBorder borderBottom proxy" style="width: 257px; display: none;"></span>'		
				+'	</div>'		
				+'	<div class="box txtProto panelChild" data-role="txtProto" style="position: absolute; min-height: 0.3rem; z-index: 0; font-size: 0.24rem; height: auto; width: auto; text-align: left; top: 171.882px; left: 27.6586px; max-width: 100%; word-wrap: break-word; cursor: move; color: rgb(0, 0, 0);" iscount="true">'			
				+'		<div class="txtShuru" style="height: 100%; min-height: 0.3rem; width: 100%; background-color: transparent;">'				
				+'			活动内容'			
				+'		</div>'			
				+'		<span class="coor proxy coorRightCenter" style="display: none;"></span>'				
				+'		<span class="objBorder borderLeft proxy" style="height: 31px; display: none;"></span>'			
				+'		<span class="objBorder borderRight proxy" style="height: 31px; display: none;"></span>'			
				+'		<span class="objBorder borderTop proxy" style="width: 96px; display: none;"></span>	'		
				+'		<span class="objBorder borderBottom proxy" style="width: 96px; display: none;"></span>'		
				+'	</div>'		
				+'	<div class="box txtProto panelChild" data-role="txtProto" style="position: absolute; min-height: 0.3rem; z-index: 0; font-size: 0.24rem; height: auto; width: auto; text-align: left; top: 211.851px; left: 24.5817px; max-width: 100%; word-wrap: break-word; cursor: move; color: rgb(153, 153, 153);" iscount="true">'			
				+'		<div class="txtShuru" style="height: 100%; min-height: 0.3rem; width: 100%; background-color: transparent;">'				
				+'			1，使用手机号码登录汽车超人APP即可领取'			
				+'		</div>'			
				+'		<span class="coor proxy coorRightCenter" style="display: none;"></span>'				
				+'		<span class="objBorder borderLeft proxy" style="height: 31px; display: none;"></span>'			
				+'		<span class="objBorder borderRight proxy" style="height: 31px; display: none;"></span>'			
				+'		<span class="objBorder borderTop proxy" style="width: 468px; display: none;"></span>'			
				+'		<span class="objBorder borderBottom proxy" style="width: 468px; display: none;"></span>	'	
				+'	</div>'		
				+'	<div class="box txtProto panelChild" data-role="txtProto" style="position: absolute; min-height: 0.3rem; z-index: 0; font-size: 0.24rem; height: auto; width: auto; text-align: left; top: 247.21px; left: 24.589px; max-width: 100%; word-wrap: break-word; cursor: move; color: rgb(153, 153, 153);" iscount="true">'			
				+'		<div class="txtShuru" style="height: 100%; min-height: 0.3rem; width: 100%; background-color: transparent;">'				
				+'			2，每位用户(同一手机号、同一微信号、同一设备等)<br>限领1份'			
				+'		</div>'			
				+'		<span class="coor proxy coorRightCenter" style="display: none;"></span>	'		
				+'		<span class="objBorder borderLeft proxy" style="height: 62px; display: none;"></span>'			
				+'		<span class="objBorder borderRight proxy" style="height: 62px; display: none;"></span>'			
				+'		<span class="objBorder borderTop proxy" style="width: 558px; display: none;"></span>'			
				+'		<span class="objBorder borderBottom proxy" style="width: 558px; display: none;"></span>'		
				+'	</div>'		
				+'	<div class="box txtProto panelChild" data-role="txtProto" style="position: absolute; min-height: 0.3rem; z-index: 0; font-size: 0.24rem; height: auto; width: auto; text-align: left; top: 319.547px; left: 23.0228px; max-width: 100%; word-wrap: break-word; cursor: move; color: rgb(153, 153, 153);" iscount="true">'			
				+'		<div class="txtShuru" style="height: 100%; min-height: 0.3rem; width: 100%; background-color: transparent;">'			
				+'			3，红包自动放到账户中，登录汽车超人APP即可使用'		
				+'		</div>'		
				+'		<span class="coor proxy coorRightCenter" style="display: none;"></span>'		
				+'		<span class="objBorder borderLeft proxy" style="height: 31px; display: none;"></span>'			
				+'		<span class="objBorder borderRight proxy" style="height: 31px; display: none;"></span>'			
				+'		<span class="objBorder borderTop proxy" style="width: 564px; display: none;"></span>'			
				+'		<span class="objBorder borderBottom proxy" style="width: 564px; display: none;"></span>'		
				+'	</div>'
				+'</div>'	
				+'<span class="objBorder borderLeft proxy" style="height: 359px; display: none;"></span>'	
				+'<span class="objBorder borderRight proxy" style="height: 359px; display: none;"></span>'	
				+'<span class="objBorder borderTop proxy" style="width: 640px; display: none;"></span>'
				+'<span class="objBorder borderBottom proxy" style="width: 640px; display: none;"></span>'	
				+'<span class="coor coorBottomRight  proxy" style="display: none;"></span>'
				+'</div>'
	var $label = $(strLabel);
	BaseOpera.AddDom($label);
	//事件绑定
	drag($('.rulerWrap .dragImg'),'bg',true);
	drag($('.rulerWrap .txtProto'),'txt',true);
	drag($('.rulerWrap .buttonProto'),'bg',true);
	drag($('.rulerWrap .panelProto'),'bg',true);
	$('.rulerWrap .box').trigger('click');
	$label.trigger('click');
	drag($label,'bg',false);
	BaseOpera('rulerWrap').RightProto();
	domhistory.pushData("new",__this);
}